# Generated by Django 5.0.1 on 2024-07-16 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('capacity', models.SmallIntegerField(default=6)),
                ('lobby_name', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('player', models.CharField(default='', max_length=16)),
                ('wins', models.IntegerField()),
                ('ingame', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='palace.game')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_zone', models.CharField(choices=[('game', 'GAME'), ('mafia', 'MAFIA'), ('private', 'PRIVATE')], default='data', max_length=16)),
                ('is_vote', models.BooleanField()),
                ('is_status', models.BooleanField()),
                ('message', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='palace.game')),
                ('private_recipient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='received', to='palace.player')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent', to='palace.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(related_name='winners', to='palace.player'),
        ),
    ]
