# Generated by Django 5.0.1 on 2024-01-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='slug',
        ),
        migrations.AddField(
            model_name='player',
            name='player',
            field=models.CharField(default='', max_length=16),
        ),
    ]
