# Generated by Django 5.0.1 on 2024-01-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palace', '0002_remove_player_slug_player_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('capacity', models.SmallIntegerField(default=6)),
                ('lobby_name', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='ingame',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='palace.lobby'),
        ),
    ]
