# Generated by Django 5.0.1 on 2024-01-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palace', '0004_alter_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ingame',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='palace.lobby'),
        ),
    ]
